runmode: release                  # debug, release, test
port: :8080

mysql:
  addr: 127.0.0.1:3306
  username: root
  password: root
  datebase: test
  maxidle: 1000
  maxoper: 1000
  maxlifetime: 1000

redis:
  addr: 127.0.0.1:6379
  password:
  maxidle: 1000
  maxactive: 1000